### ISSUE TITLE
Listing Python `futures` in red is FUD.

### ISSUE THREAD

**Issue by ztane** [ubershmekel/python3wos#11]
7th red on the list is `futures` which is a backport of Python 3.2+ concurrent.futures to Python 2... along with a lock stating that "this project will not be seen on Python 3 in foreseeable future"...

**Comment by flying-sheep** [comment]
why “FUD”? that implies that @ubershmekel somehow wants it like that.

i’d say it’s an artifact.

**Comment by waldyrious** [comment]
@flying-sheep sure, that's just a semantic distinction. The important thing is the impression this causes in users who see an extra red entry indicating less readiness than what there really is. That's indeed FUD-ish in effect, although not in intent :)
