### ISSUE TITLE
suds is no longer maintained. suds-jurko is its successor

### ISSUE THREAD

**Issue by fuhrysteve** [ubershmekel/python3wos#13]
Jurko's fork has been actively maintained for several years now, while the original suds library has long been abandoned by the original maintainer.

https://bitbucket.org/jurko/suds

https://pypi.python.org/pypi/suds-jurko

suds-jurko is py3k ready

**Comment by ubershmekel** [comment]
I believe this is fixed now. Thank you for reporting.
