### ISSUE TITLE
Last update was over 2 months ago

### ISSUE THREAD

**Issue by ushuz** [ubershmekel/python3wos#22]
![image](https://cloud.githubusercontent.com/assets/1430856/13252613/b7b93b7e-da72-11e5-9bcc-eba009c02259.png)

Today is 2016-02-23, the wall was updated at 2015-12-14, it's over 2 months ago. Maybe scheduled tasks went wrong? 

https://python3wos.appspot.com/

**Comment by tuxayo** [comment]
+1 I'm eager to know the migration progress of the ecosystem to Python 3

**Comment by ztane** [comment]
4 months.

**Comment by cclauss** [comment]
@ubershmekel This update needs to be run... This site now paints a darker picture of Python 3 adoption than it should!!

**Comment by ubershmekel** [comment]
Sorry I didn't notice. I'll look into it in the next few days.

**Comment by ztane** [comment]
@ubershmekel a cronjob would be nice :D

**Comment by ubershmekel** [comment]
@ztane the cronjob was failing. See https://github.com/ubershmekel/python3wos/commit/3224e8ebf363efac9dca4f80711b73e39d4670e3 for more info. I'm not sure what happened in December - if pypi started responding slowly, or if google changed something. If nothing else is broken - we should see the last updated timestamp climb up slowly during the next few days while all of pypi is crawled.

**Comment by cclauss** [comment]
@ubershmekel Is it working?  The timestamp on the website is not yet moving?  Is it correct that the `main()` function of https://github.com/ubershmekel/python3wos/blob/master/pypi_parser.py is never called!?!

**Comment by ztane** [comment]
OK, now it is updating *something*, used to be 2015-12-14, now 2015-12-16.

**Comment by ubershmekel** [comment]
There was another problem with certain packages failing to update and thus blocking the update list.

@cclauss to follow what gets called in this google app engine cron you go to `cron.yaml` there you see `url: /tasks/update` which takes you to https://github.com/ubershmekel/python3wos/blob/master/wsgi.app which mentions `('/tasks/update', pypi_cron.CronUpdate),`

So this gets called every 3 minutes: https://github.com/ubershmekel/python3wos/blob/master/pypi_cron.py#L95

The main function is just for my local testing.

**Comment by ubershmekel** [comment]
And now we've hit this gem:

`OverQuotaError: The API call datastore_v3.Put() required more quota than is available.`

Maybe I should just give up on updating the counts for all of PyPI. I'm trying to track 19K packages just to show the top 200.

**Comment by ushuz** [comment]
@ubershmekel I guess crawling the top 200 would be enough.

**Comment by cclauss** [comment]
My quick and dirty script finds 27 modules in the top 200 scripts still do not support Python3.  86.5% support Python3 and that is without removing certain modules as the WOS script does.  Nice progress...

https://github.com/cclauss/uncategorized_hacks/blob/master/pypi_top200.py

```
27 Python 2 ONLY packages:
Module name                   Latest       Python 3?
===========                   ======       =========
bcdoc                         0.16.0       False
supervisor                    3.3.0        False
MySQL-python                  1.2.5        False
carbon                        0.9.15       False
futures                       3.0.5        False
ssl                           1.16         False
graphite-web                  0.9.15       False
Fabric                        1.11.1       False
unittest2                     1.1.0        False
ordereddict                   1.1          False
ipaddress                     1.0.16       False
mozrunner                     6.11         False
moznetwork                    0.27         False
mozdevice                     0.48         False
mozprofile                    0.28         False
mozprocess                    0.22         False
mozfile                       1.2          False
mozinfo                       0.9          False
mozlog                        3.2          False
mozcrash                      0.17         False
suds                          0.4          False
python-gflags                 3.0.5        False
ndg-httpsclient               0.4.0        False
thrift                        0.9.3        False
BeautifulSoup                 3.2.1        False
requests-oauthlib             0.6.1        False
functools32                   3.2.3-2      False
```

**Comment by ubershmekel** [comment]
I've added a cron to crawl the top packages more frequently. Within 2 days, the chart should fully update daily.

https://github.com/ubershmekel/python3wos/blob/master/cron.yaml#L7

**Comment by cclauss** [comment]
@ubershmekel I think that we can close this issue.

We can also close issue https://github.com/ubershmekel/python3wos/issues/16

If we implement `equivalents` like what is in pull request https://github.com/ubershmekel/python3wos/pull/26 then I believe that we can close issues https://github.com/ubershmekel/python3wos/issues/13 https://github.com/ubershmekel/python3wos/issues/23 and https://github.com/ubershmekel/python3wos/issues/27

**Comment by cclauss** [comment]
@ushuz Can you please click `Close` on this issue?

**Comment by ushuz** [comment]
@cclauss Closed.
