### ISSUE TITLE
uWSGI and ReportLab both support Python 3

### ISSUE THREAD

**Issue by awilfox** [ubershmekel/python3wos#23]
ReportLab supports Python 3.3+ since [version 3.0](http://www.reportlab.com/documentation/relnotes/30/), released back in 2014.

uWSGI supports Python 3.2+ for at least a year, but their documentation is hard to find an exact date/release.  Suffice it to say, it should be green too.

**Comment by ztane** [comment]
See https://github.com/ubershmekel/python3wos/issues/15

**Comment by cclauss** [comment]
ReportLab is now green.  Still waiting on uWSGI...

**Comment by cclauss** [comment]
Eventhough the uWSGI folks did their piece...  https://github.com/unbit/uwsgi/issues/1275 ...WoS is still showing uWSGI as `red`.

**Comment by cclauss** [comment]
@awilfox or @ubershmekel Please click "Close" on this issue as both ReportLab and uWSGI are now green.

**Comment by awilfox** [comment]
Great!  Thank you.
