### ISSUE TITLE
Remove "FUD" line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ubershmekel/python3wos#4]
```
py3ksupport.appspot.com has been shut down so the link and comment is 
unnecessary.
```

Original issue reported on code.google.com by `bcannon` on 13 Aug 2013 at 9:17

Attachments:
* [index_db.html.patch](https://storage.googleapis.com/google-code-attachments/python3wos/issue-4/comment-0/index_db.html.patch)

**Comment by ubershmekel** [comment]
Removed
