### ISSUE TITLE
python-gflags description

### ISSUE THREAD

**Issue by Marqin** [ubershmekel/python3wos#47]
near `python-gflags` it's written:

> The maintainers of this package have declared it will work only on Python 2 for the foreseeable future

But maintainers of that project say that they are working on Python3 compability and it should be released [soon](https://github.com/google/python-gflags/issues/28#issuecomment-247525912).

**Comment by ubershmekel** [comment]
`Programming Language :: Python :: 2 :: Only` is mentioned at https://pypi.python.org/pypi/python-gflags/3.0.7

Please contact the maintainers to remove that tag if that is not what they meant.

**Comment by cclauss** [comment]
The Python 3 trove classifiers are set in https://github.com/google/python-gflags/blob/master/setup.py#L46 and that release is on PyPI.
