### ISSUE TITLE
Update limit to 500 packages instead of 200?

### ISSUE THREAD

**Issue by cclauss** [ubershmekel/python3wos#51]
90% of the top 500 packages are now Python 3 compatible so it would be a good time to open the aperture.

**Comment by ubershmekel** [comment]
What would we gain from it being the top 500?

**Comment by cclauss** [comment]
Given the community's progress on moving to Python 3, the current page has just 13 red packages.  Two of those packages have declared in their trove classifiers that they are Python 2 Only. Nine other red packages are from Mozilla who not progressing them.

By expanding the list, we shine a light on other popular packages that could be ported to Python 3.

**Comment by cclauss** [comment]
Do not underestimate the power that your tool has...  https://bugzilla.mozilla.org/show_bug.cgi?id=1093212#c9

**Comment by ubershmekel** [comment]
* We have your version at https://python3wos.mybluemix.net/ for the top 500.
* I like attainable goals. The number `200` seems reasonable. Although it is an arbitrary target, I'm personally content with keeping it at 200 and 93.5%. Not a moving target for the community to chase.
* The statistics become less significant and more gameable at the 200-500 level.
* What after 500? Do we raise to 1000?
* Ideally, it'd be obvious that packages support python 3 and the trove classifier wasn't necessary. I'd rather think more on how the webapp should be sunset or frozen in the future. We're at Python 3.6.1, we should start thinking about Python 4. I hope the lesson was learned and we won't fracture the community the way 2-to-3 did.

**Comment by cclauss** [comment]
Understood...  See the lower left of https://pypi.org/project/requests to understand how trove classifiers will help users to find packages that fit there needs in warehouse which will soon replace PyPI.
